name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: "Slack notification (not success)"
      uses: homoluctus/slatify@master
      if: "! success()"
      with:
        type: ${{ job.status }}
        username: GitHub Actions (Failure)
        job_name: ":atlassian::rust: Tests"
        mention: channel
        mention_if: always
        icon_emoji: "github"
        url: ${{ secrets.SLACK_WEBHOOK }}

    - name: "Slack Notification (success)"
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        username: GitHub Actions (Success)
        job_name: ":atlassian::rust: Tests"
        icon_emoji: ":github:"
        url: ${{ secrets.SLACK_WEBHOOK }}
