name: Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: docker run -e CARGO_HOME=/home/rust/.cargo -e RUSTUP_HOME=/home/rust/.rustup --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder cargo build --release
