name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build static
      uses: stevenleadbeater/rust-musl-builder@master
      with:
          args: /bin/bash -c "cargo build --release --target=x86_64-unknown-linux-musl"

    - uses: actions/upload-artifact@v2
      with:
        name: atlrus
        path: target/x86_64-unknown-linux-musl/release/atlrus

    - name: "Slack notification (not success)"
      uses: homoluctus/slatify@master
      if: "! success()"
      with:
        type: ${{ job.status }}
        username: GitHub Actions (Failure)
        job_name: ":atlassian::rust: Release"
        mention: channel
        mention_if: always
        icon_emoji: "github"
        url: ${{ secrets.SLACK_WEBHOOK }}

    - name: "Slack Notification (success)"
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        username: GitHub Actions (Success)
        job_name: ":atlassian::rust: Release"
        icon_emoji: ":github:"
        url: ${{ secrets.SLACK_WEBHOOK }}
